accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView
# from django.contrib.auth import views as auth_views




app_name = 'accounts'

urlpatterns = [
	path('signup/', views.signup_view, name='signup'),
	path('login/', views.login_view, name='login'),
	path('logout/', views.logout_view, name='logout'),
	path('profile/', views.profile_view, name='profile'),
	path('profile/edit/', views.edit_profile, name='edit_profile'),
	path('change-password/', views.change_password, name='change_password'),
	path('update_profile/', views.update_profile, name='update_profile'),
	path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
	path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
	path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),



] 

fastgigafrica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('digitalmarket/', include('digitalmarket.urls')),
    path('educationwriting/', include('educationwriting.urls')),
    path('graphicdesign/', include('graphicdesign.urls')),
    path('programming/', include('programming.urls')),
    path('techbusiness/', include('techbusiness.urls')),
    path('videoanimation/', include('videoanimation.urls')),
    path('orderpay/', include('orderpay.urls')),
    # path('offerapost/', include('offerapost.urls')),
    # path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .import views


app_name = 'home'

urlpatterns = [
	path('', views.index, name='index'),
	path('dashboard/', views.dashboard, name='dashboard'),
	path('offerapost/', views.offerapost, name='offerapost'),
	path('manageorder/', views.manageorder, name='manageorder'),
	path('jobdetails/', views.jobdetails, name='jobdetails'),
	# path('offerapost/', views.offerapost, name='offerapost'),
    path('offerapost2/', views.offerapost2, name='offerapost2'),
    path('offerapost3/', views.offerapost3, name='offerapost3'),
    path('offerapost4/', views.offerapost4, name='offerapost4'),
    path('orderconfirm/', views.orderconfirm, name='orderconfirm'),
	

] 

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from . import signals



class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	description = models.TextField(max_length=500, default='')
	city = models.CharField(max_length=100, default='')
	skill = models.CharField(max_length=100, default='')
	
   
	
	

	def __str__(self):
		return self.user.username

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)		


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    skill = models.CharField(max_length=500, default='')
    education = models.CharField(max_length=100, default='')
    certifications = models.CharField(max_length=300, default='')
    social = models.URLField(max_length=100, default='')
    website = models.URLField(default='')
    location = models.CharField(max_length=100, default='')
    phone = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    photo = models.ImageField(null=True, blank=True)
	


    def __str__(self):
    	return "Profile of user {}". format(self.user)




def create_profile(sender, **kwargs):
	if kwargs['created']:
	    user_profile = Profile.objects.create(user=kwargs['instance'])
	pass

post_save.connect(create_profile, sender=User)   	



@property
def photo_url(self):
    if self.photo and hasattr(self.photo, 'url'):
        return self.photo.url

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
from .models import Profile



#Form extension to the signup page
class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


#Form extension to the edit profile page
class EditProfileForm(UserChangeForm):

	
	class Meta:
		model = User
		fields = ('email', 'first_name', 'last_name', 'password')
		# exclude = ('username','password',)    




class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'email',)


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)        

accounts/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.core.files.storage import FileSystemStorage
from . models import UserProfile, Profile
from django.contrib.auth.decorators import login_required
from accounts.forms import SignUpForm, EditProfileForm, UserEditForm, ProfileEditForm


# Create your views here.
def signup_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            # Profile.objects.create(user=new_user)
            return redirect('home:index')
    else:
        form = SignUpForm()
    return render(request, 'accounts/signup.html', {'form': form})

def login_view(request):
	if request.method == 'POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			#Log in the User
			user = form.get_user()
			login(request, user)
			return redirect('home:dashboard')
	else:
		form = AuthenticationForm()	
	return render(request, 'accounts/login.html', {'form':form})


def logout_view(request):
	if request.method == 'POST':
		logout(request)
	return redirect('home:index')
	

def profile_view(request):
	args = {'user': request.user}
	return render(request, 'accounts/profile.html', args)


def edit_profile(request):
	if request.method =='POST':
		form = EditProfileForm(request.POST, request.FILES, instance=request.user)
		if form.is_valid():
			form.save()
			return redirect('accounts:edit_profile')

	else:
		form = EditProfileForm(instance=request.user)
		args = {'form':form}
		return render(request, 'accounts/edit_profile.html', args)			

def change_password(request):
	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)

		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			return redirect('accounts:profile')
		else:
			return redirect('accounts:change-password')	

	else:
		form = PasswordChangeForm(user=request.user)
		args = {'form':form}
		return render(request, 'accounts/change_password.html', args)		



@login_required
# @transaction.atomic
def update_profile(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST or None, instance=request.user)
        profile_form = ProfileEditForm(request.POST or None, instance=request.user.profile, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            
            return redirect('home:dashboard')
       
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    return render(request, 'accounts/update_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

accounts/templates/accounts/change_password.html
{% load static %}
<head>
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}">

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
{% block body %}
<ul class="nav justify-content-end">
      <li class="nav-item">
        <form class="nav-link" action="{% url 'home:index' %}" method="post">
                {%csrf_token%}
                <button type="submit" class="btn btn-flat" style="padding:10px; text-align:center; word-spacing: 40px; width: 100px; background-color: #fff;">Email</button>
              </form>
      </li>
      <li class="nav-item">
        <form class="nav-link" action="{% url 'home:index' %}" method="post">
                {%csrf_token%}
                <button type="submit" class="btn btn-flat" style="padding:10px; text-align:center; word-spacing: 40px; width: 100px; background-color: #fff;">Sms</button>
              </form>
      </li>

      <li class="nav-item">
        <form class="nav-link" action="{% url 'accounts:profile' %}" method="post">
                {%csrf_token%}
                <button type="submit" class="btn btn-flat" style="padding:10px; text-align:center; word-spacing: 40px; width: 100px; background-color: #e83e8c;">Profile</button>
              </form>
      </li>
      <li class="nav-item">
        <form class="nav-link" action="{% url 'accounts:logout' %}" method="post">
                {%csrf_token%}
                <button type="submit" class="btn btn-flat" style="padding:10px; text-align:center; word-spacing: 40px; width: 100px; background-color: #fff;">Logout</button>
              </form>
      </li>
  </ul>


<div class="container" >
		<div class="space-20"></div>
		        <center>
		            <img src="{% static 'img/logo.png'%}" width="100px">
		        </center>
        <div class="space-20"></div>

		
		<form method="post">
		{% csrf_token%}
		{{ form.as_p}}
		<button type="submit">Submit</button>
		</form>

{%endblock%}

accounts/templates/accounts/login.html
{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <title>Raxio - Micro Freelancing Marketplace</title>
    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'img/fav.jpg'%}" type="image/x-icon">
    <!--Google Font-->
    <link href="{% static 'googleapis.css'%}" rel="stylesheet">
    <!--Bootstrap Stylesheet-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css'%}">
    <!--Main Stylesheet-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/logReg.css'%}">
    <!-- Responsive  Stylesheet-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css'%}">


</head>

<body class="body-class reglog">
    {% block content %}
    <div class="overlay"></div>
    <!--Start Body Wrap-->
    <div id="body-wrap">

        <!-- ============ Register area start =============== -->

        <section id="register">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center r-logo">
                        <a href="{% url 'home:index' %}">
                            <h2 style="color: #fff; font-weight: 400; font-family: sans-serif;">Fast gig africa</h2>
                        </a>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="reg-box">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="worker-tab" data-toggle="tab" href="#worker" role="tab" aria-controls="worker"
                                     aria-selected="true">
                                        As a Woker
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="buyer-tab" data-toggle="tab" href="#buyer" role="tab" aria-controls="buyer"
                                     aria-selected="false">
                                        As a Buyer
                                    </a>
                                </li>
                            </ul>
                            <div class="tab-content" id="myTabContent">
                                <div class="tab-pane fade show active" id="worker" role="tabpanel" aria-labelledby="worker-tab">
                                        <form action="{% url 'accounts:login'%}" method="post">
                                            {% csrf_token %}   
                                               <p>
                                                <label for="id_username">Username:</label><br>
                                                <input type="text" name="username" autofocus required id="id_username" class="mamunur_rashid_form">
                                                
                                              </p>
                                            
                                              <p>
                                                <label for="id_password">Password:</label><br>
                                                <input type="password" name="password" required id="id_password" class="mamunur_rashid_form">
                                                
                                              </p>
                                    
                                            <div class="form-group row mb-0">
                                                    <div class="col-md-6 offset-md-4">
                                                        <button type="submit" class="mr_button" style="text-align: center;">
                                                            Login
                                                        </button>
                                                    </div>
                                            </div>
                                        </form>
                                        <div class="row">
                                        <div class="col d-flex justify-content-between  mr-d-block">
                                            <div class="left">
                                                <p>Not A Member Yet ? <a href="{% url 'accounts:signup'%}">Signup</a></p>
                                            </div>
                                            <div class="right">
                                                <a href="{% url 'accounts:password_reset'%}">Forget Password ?</a>
                                            </div>
                                        </div>
                                    </div>
                                
                                    <div class="row fb_tw">
                                        <div class="col-sm-6">
                                            <a href="#" class="mr_button mr_button2">Register With Facebook</a>
                                        </div>
                                        <div class="col-sm-6">
                                            <a href="#" class="mr_button mr_button3">Register With Facebook</a>
                                        </div>
                                    </div>

                                </div>
                                <div class="tab-pane fade" id="buyer" role="tabpanel" aria-labelledby="buyer-tab">
                                    <form>
                                        {%csrf_token%}
                                        <div class="row">
                                            <div class="col">
                                                <input type="email" class="mamunur_rashid_form" placeholder="Your Email...">
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <input type="password" class="mamunur_rashid_form" placeholder="Password...">
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <button type="submit" class="mr_button">Register Now</button>
                                            </div>
                                        </div>
                                    </form>
                                    <div class="row">
                                        <div class="col d-flex justify-content-between mr-d-block">
                                            <div class="left">
                                                <p>Not A Member Yet ? <a href="{% url 'accounts:signup'%}">Register Now</a></p>
                                            </div>
                                            <div class="right">
                                                <a href="#">Forget Password ?</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row fb_tw">
                                        <div class="col-sm-6">
                                            <a href="#" class="mr_button mr_button2">Register With Facebook</a>
                                        </div>
                                        <div class="col-sm-6">
                                            <a href="#" class="mr_button mr_button3">Register With Facebook</a>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- ============ Register area start =============== -->


        <!--Start ClickToTop-->
        <div class="totop">
            <a href="#top"><i class="fa fa-arrow-up"></i></a>
        </div>
        <!--End ClickToTop-->
    </div>
    <!--End Body Wrap-->
    <!--jQuery JS-->
    <script src="{% static 'js/jquery.2.1.2.min.js'%}"></script>
    <!--Bootstrap JS-->
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
{% endblock%}
</body>

accounts/templates/accounts/logout.html
{%block content%}
<h1>Logout</h1>
{%endblock%}

accounts/templates/accounts/password_reset.html
{% block content %}
  <h3>Forgot password</h3>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
  </form>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% block content %}
  {% if validlink %}
    <h3>Change password</h3>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Change password</button>
    </form>
  {% else %}
    <p>
      The password reset link was invalid, possibly because it has already been used.
      Please request a new password reset.
    </p>
  {% endif %}
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% block content %}
  <p>
    We've emailed you instructions for setting your password, if an account exists with the email you entered.
    You should receive them shortly.
  </p>
  <p>
    If you don't receive an email, please make sure you've entered the address you registered with,
    and check your spam folder.
  </p>
{% endblock %}

accounts/templates/accounts/signup.html
{%load static%}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <title>Raxio - Micro Freelancing Marketplace</title>
    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'img/fav.jpg'%}" type="image/x-icon">

    <link rel="stylesheet" type="text/css" href="{% static 'css/logReg.css'%}">

    <link href="{% static 'css/googleapis.css' %}" rel="stylesheet">
 <!--Bootstrap Stylesheet-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
    
    <!--Font Awesome Stylesheet-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css'%}">
    
    <!--Main Stylesheet-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style1.min.css'%}">
    <!--Responsive Stylesheet-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.min.css'%}">

</head>

<body class="body-class reglog">
    {% block content %}

    <div class="overlay"></div>
    <!--Start Body Wrap-->
    <div id="body-wrap">

        <!-- ============ Register area start =============== -->

        <section id="register">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center r-logo">
                        <a href="{% url 'home:index' %}"><img src="{% static 'img/whitelogo.png'%}" alt=""></a>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="reg-box">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="worker-tab" data-toggle="tab" href="#worker" role="tab" aria-controls="worker"
                                     aria-selected="true">
                                        As a Woker
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="buyer-tab" data-toggle="tab" href="#buyer" role="tab" aria-controls="buyer"
                                     aria-selected="false">
                                        As a Buyer
                                    </a>
                                </li>
                            </ul>
                            <div class="tab-content" id="myTabContent">
                                <div class="tab-pane fade show active" id="worker" role="tabpanel" aria-labelledby="worker-tab">
                                    <form action="/accounts/signup/" method="post">
                                        {% csrf_token %}
                                         
                                            <div class="row">
                                            <div class="col-sm-6">

                                      <p>
                                        <label for="id_username">Username:</label><br>
                                        <input type="text" class="mamunur_rashid_form" name="username" maxlength="150" autofocus required id="id_username">
                                        
                                      </p>
                                       </div>

                                        <div class="col-sm-6">
                                      <p>
                                        <label for="id_email">Email:</label><br>
                                        <input type="email" class="mamunur_rashid_form" name="email" maxlength="254" required id="id_email">
                                        
                                      </p>
                                  </div>
                                    <div class="col-sm-6">
                                      <p>
                                        <label for="id_password1">Password:</label><br>                      
                                        <input type="password" class="mamunur_rashid_form" name="password1" required id="id_password1">
                                        
                                      </p>
                                  
                                  </div>
                                       <div class="col-sm-6"> 
                                      <p>
                                        <label for="id_password2">Password confirmation:</label><br>    
                                        <input type="password" class="mamunur_rashid_form" name="password2" required id="id_password2">
                                        
                                      </p>
                                    </div>
                                    </div>
                                        <div class="form-group row mb-0">
                                                <div class="col-md-6 offset-md-4">
                                                    <button type="submit" class="mr_button">
                                                        Sign Up
                                                    </button>
                                                </div>
                                            </div>
                                         
                                    </form>
                                    <div class="row">
                                        <div class="col text-center">
                                            <p>Already A Member ? <a href="login.html">Log In Here</a></p>
                                        </div>
                                    </div>
                                    <div class="row fb_tw">
                                        <div class="col-sm-6">
                                            <a href="#" class="mr_button mr_button2">Register With Facebook</a>
                                        </div>
                                        <div class="col-sm-6">
                                            <a href="#" class="mr_button mr_button3">Register With Facebook</a>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="buyer" role="tabpanel" aria-labelledby="buyer-tab">
                                    <form>
                                        <div class="row">
                                            <div class="col-sm-6">
                                                <input type="text" class="mamunur_rashid_form" placeholder="First name...">
                                            </div>
                                            <div class="col-sm-6">
                                                <input type="text" class="mamunur_rashid_form" placeholder="Last name...">
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <input type="email" class="mamunur_rashid_form" placeholder="Your Email...">
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <input type="password" class="mamunur_rashid_form" placeholder="Password...">
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <button type="submit" class="mr_button">Register Now</button>
                                            </div>
                                        </div>
                                    </form>
                                    <div class="row">
                                        <div class="col text-center">
                                            <p>Already A Member ? <a href="{% url 'accounts:login'%}">Log In Here</a></p>
                                        </div>
                                    </div>
                                    <div class="row fb_tw">
                                        <div class="col-sm-6">
                                            <a href="#" class="mr_button mr_button2">Register With Facebook</a>
                                        </div>
                                        <div class="col-sm-6">
                                            <a href="#" class="mr_button mr_button3">Register With Facebook</a>
                                        </div>
                                    </div>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <!-- ============ Register area start =============== -->


        <!--Start ClickToTop-->
        <div class="totop">
            <a href="#top"><i class="fa fa-arrow-up"></i></a>
        </div>
        <!--End ClickToTop-->
    </div>
    <!--End Body Wrap-->
    <!--jQuery JS-->
    <script src="js/jquery.2.1.2.min.js"></script>
    <!--Bootstrap JS-->
    <script src="js/bootstrap.min.js"></script>
    <!--Main-->
{%endblock%}
</body>

accounts/templates/accounts/simple_upload.html
{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile" id="document.id">
    <button type="submit">Upload</button>
  </form>

  {% if uploaded_file_url %}
    <p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>
  {% endif %}

  <p><a href="{% url 'sendText:index' %}">Return to home</a></p>
{% endblock %}

accounts/templates/accounts/update_profile.html
{% block content%}

<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
{{ user_form.as_p }}
{{ profile_form.as_p}}
<input type="submit" value="Save Changes" class="btn btn-outline-success">
</form>
{% endblock%}