accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView
# from django.contrib.auth import views as auth_views




app_name = 'accounts'

urlpatterns = [
	path('signup/', views.signup_view, name='signup'),
	path('login/', views.login_view, name='login'),
	path('logout/', views.logout_view, name='logout'),
	path('profile/', views.profile_view, name='profile'),
	path('profile/edit/', views.edit_profile, name='edit_profile'),
	path('change-password/', views.change_password, name='change_password'),
	path('update_profile/', views.update_profile, name='update_profile'),
	path('password-reset/', PasswordResetView.as_view(), name='password_reset'),
	path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
	path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),



] 

digitalmarket/urls.py
from django.urls import path
from . import views

app_name = 'digitalmarket'

urlpatterns = [
    path('create/', views.post_create, name='create'),
    path('list/', views.post_list, name='list'),
    path('detail/', views.post_detail, name='detail'),
    path('confirm/', views.post_confirm, name='confirm'),
    path('review/', views.post_review, name='review'),
    
]

fastgigafrica/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('accounts/', include('accounts.urls')),
    path('digitalmarket/', include('digitalmarket.urls')),
    path('educationwriting/', include('educationwriting.urls')),
    path('graphicdesign/', include('graphicdesign.urls')),
    path('programming/', include('programming.urls')),
    path('techbusiness/', include('techbusiness.urls')),
    path('videoanimation/', include('videoanimation.urls')),
    path('orderpay/', include('orderpay.urls')),
    # path('offerapost/', include('offerapost.urls')),
    # path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

graphicdesign/urls.py
from django.urls import path
from .import views

app_name = 'graphicdesign'

urlpatterns = [
    path('create/', views.post_create, name='create'),
    path('list/', views.post_list, name='list'),
    path('detail/', views.post_detail, name='detail'),
    path('confirm/', views.post_confirm, name='confirm'),
    path('review/', views.post_review, name='review'),
    
]

home/urls.py
from django.urls import path
from .import views


app_name = 'home'

urlpatterns = [
	path('', views.index, name='index'),
	path('dashboard/', views.dashboard, name='dashboard'),
	path('offerapost/', views.offerapost, name='offerapost'),
	path('manageorder/', views.manageorder, name='manageorder'),
	path('jobdetails/', views.jobdetails, name='jobdetails'),
	# path('offerapost/', views.offerapost, name='offerapost'),
    path('offerapost2/', views.offerapost2, name='offerapost2'),
    path('offerapost3/', views.offerapost3, name='offerapost3'),
    path('offerapost4/', views.offerapost4, name='offerapost4'),
    path('orderconfirm/', views.orderconfirm, name='orderconfirm'),
	

] 

techbusiness/urls.py
from django.urls import path
from . import views

app_name = 'techbusiness'

urlpatterns = [
	path('post/', views.post, name='post'),
    path('create/', views.post_create, name='create'),
    path('list/', views.post_list, name='list'),
    path('detail/', views.post_detail, name='detail'),
    path('confirm/', views.post_confirm, name='confirm'),
    path('review/', views.post_review, name='review'),
    
]

videoanimation/urls.py
from django.urls import path
from . import views

app_name = 'videoanimation'

urlpatterns = [
    path('create/', views.post_create, name='create'),
    path('list/', views.post_list, name='list'),
    path('detail/', views.post_detail, name='detail'),
    path('confirm/', views.post_confirm, name='confirm'),
    path('review/', views.post_review, name='review'),
    
]

digitalmarket/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from accounts.models import Profile


class Category(models.Model):
    name = models.CharField(max_length=200)   

    def __str__(self):
        return self.name


class Sub_Category(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name



class Postdigit(models.Model):
    title = models.CharField(max_length=255, default='')
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    sub_category = models.ForeignKey(Sub_Category,on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    response_time = models.TimeField(blank=True)
    slug = models.SlugField(max_length=250)
    requirement = models.TextField()
    author = models.ForeignKey(User, blank=True,on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    gallery = models.ImageField(null=True, blank=True)
    delivery = models.CharField(max_length=120, default=0)
    

    

    def __str__(self):
        return self.title

    

class Confirm(models.Model):
    title = models.CharField(max_length=255, default='')
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    sub_category = models.ForeignKey(Sub_Category,on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    subtotal = models.DecimalField(max_digits=6, decimal_places=2)
    service = models.DecimalField(max_digits=6, decimal_places=5)
    quantity = models.IntegerField()
    total = models.DecimalField(max_digits=6, decimal_places=4)
    requirement = models.TextField()
    author = models.ForeignKey(User, blank=True,on_delete=models.CASCADE)
    gallery = models.ImageField(null=True, blank=True)

 


    def __str__(self):
        return self.title





class Reviewdigit(models.Model):
    name = models.CharField(max_length=1024)
    text = models.TextField()
    author = models.ForeignKey(Profile,on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)


    price_rating = models.IntegerField(null=True)
    location_rating = models.IntegerField(null=True)

    def __str__(self):
        return self.name    	

digitalmarket/forms.py
from django import forms
from . import models
from .models import Reviewdigit
from django.contrib.auth.models import User


class CreatePost(forms.ModelForm):
	class Meta:
		model = models.Postdigit
		fields = ['title','category','sub_category', 'response_time', 'price','requirement','gallery', 'delivery']

class Confirm(forms.ModelForm):
	class Meta:
		model = models.Confirm
		fields = ['title', 'subtotal', 'price','requirement','gallery', 'total', 'quantity']



class CreateReview(forms.ModelForm):
	class Meta:
		model = models.Reviewdigit
		fields = ['name','author','text','price_rating','location_rating']

digitalmarket/views.py
from django.shortcuts import render, redirect
from . import views
from django.http import HttpResponse
from .models import Postdigit, Reviewdigit, Confirm
from django.contrib.auth.decorators import login_required
from .import forms
from django.shortcuts import get_object_or_404


# Create your views here.

def post_list(request):
    posts =  Postdigit.objects.all().order_by('date')
    return render(request, 'digital/post_list.html', {'posts': posts})

def post_detail(request):
    post = Postdigit.objects.get()
    return render(request, 'digital/post_detail.html', {'post': post})    

@login_required(login_url='/accounts/login')
def post_create(request):
	if request.method == 'POST':
		form = forms.CreatePost(request.POST,request.FILES)
		if form.is_valid():
			#save post to db
			instance = form.save(commit=False)
			instance.author = request.user
			instance.save()
			return redirect('posts:list')

	else:	
		form = forms.CreatePost()
	return render(request, 'digital/post_create.html',{'form':form})


@login_required(login_url='/accounts/login')
def post_confirm(request):
	post =  Postdigit.objects.all().order_by('date')
	return render(request, 'digital/post_confirm.html', {'post':post})



def post_review(request):
	return render(request, 'digital/post_review.html', {})

digitalmarket/templates/digital/post_create.html
{%load static%}

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0">
	<meta name="keywords" content="">
	<meta name="description" content="">
	<title>Raxio - Micro Freelancing Marketplace</title>
	<!-- favicon -->
	<link rel="shortcut icon" href="{% static 'img/fav.jpg'%}" type="image/x-icon">
	<!--Google Font-->
	 <link href="{% static 'css/googleapis.css' %}" rel="stylesheet">
 <!--Bootstrap Stylesheet-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
	<!-- Animate Stylesheet-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<!--Font Awesome Stylesheet-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
	<!--Owl Carousel Stylesheet-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.min.css' %}">
	<!--Slick Slider Stylesheet-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/slick-theme.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/slick.css' %}">
	<!--Main Stylesheet-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.min.css' %}">
	<!--Responsive Stylesheet-->
	<link rel="stylesheet" type="text/css" href="{% static 'css/responsive.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/catagori.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/offerapost.css'%}">
	

</head>

<body class="body-class catagoris offer">
	{% block content %}
	<!--Start Preloader-->
	<div class="site-preloader">
		<div class="spinner">
			<div class="double-bounce1"></div>
			<div class="double-bounce2"></div>
		</div>
	</div>
	<!--End Preloader-->

	<!--Start Body Wrap-->
	<div id="body-wrap">
		<div id="main-menu">
			<nav class="navbar navbar-expand-md navbar-light">
				<div class="container">
					<a class="navbar-brand" href="{% url 'home:index'%}">
						<img src="{% static 'img/main-logo.png'%}" alt="">
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
					 aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>

					<div class="collapse navbar-collapse" id="navbarSupportedContent">
						<ul class="navbar-nav ml-auto">
							<li class="nav-item">
								<a class="nav-link" href="#banner">How Its Work</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" href="#about">About Us</a>
							</li>
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownpage" role="button" data-toggle="dropdown"
								 aria-haspopup="true" aria-expanded="false">
									Become a gig
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdownpage">
									<a class="dropdown-item" href="#">Programming & Tech</a>
									<a class="dropdown-item" href="{% url 'graphicdesign:create' %}">Graphic & Design</a>
									<a class="dropdown-item" href="{% url 'digitalmarket:create' %}">Digital Marketing</a>
									<a class="dropdown-item" href="{% url 'techbusiness:create' %}">Tech Business</a>
									<a class="dropdown-item" href="{% url 'videoanimation:create' %}">Animation & Wrting</a>							
								</div>
							</li>
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown"
								 aria-haspopup="true" aria-expanded="false">
									<div class="img d-inline-block">
										<img src="{{ user.userprofile.photo.url}}" alt="">
									</div>
									<p class="d-inline-block">{{ user.username }}</p>
								</a>
								<div class="dropdown-menu" aria-labelledby="navbarDropdown2">
									<a class="dropdown-item" href="{% url 'accounts:profile'%}">Profile</a>
                  <a class="dropdown-item" href="{% url 'home:dashboard'%}">Dashbord</a>
                  <a class="dropdown-item" href="{% url 'posts:create'%}">Post A Offer</a>
                  <a class="dropdown-item" href="{% url 'home:manageorder'%}">Manage Order</a>
                  <a class="dropdown-item" href="#">Settings</a>
                  <a class="dropdown-item" href="{% url 'accounts:logout'%}">Log Out</a>
								</div>
							</li>
						</ul>
					</div>
				</div>
			</nav>
		</div>

		<!-- =========== nav end =========== -->

		<!-- =========== mybreadcrumb Area Start =========== -->
		<section id="mybreadcrumb">
			<div class="overlay"></div>
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-lg-6">
						<div class="title_area">
							<h1>Post A Offer</h1>
							<p>It is a long established fact that a reader will be distracted by the readable content of a page when
								looking.</p>
						</div>
					</div>
				</div>
				<div class="row breadcrumb_menu">
					<div class="col-12">
						<nav class="navbar navbar-expand-lg navbar-light bg-light">
							<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent2"
							 aria-controls="navbarSupportedContent2" aria-expanded="false" aria-label="Toggle navigation">
								<span class="navbar-toggler-icon"></span>
							</button>
							<div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent2">
								<ul class="navbar-nav">
									<li class="nav-item active">
										<a class="nav-link" href="offerapost.html">Digital Marketing</a>
									</li>
									
								</ul>
							</div>
						</nav>
					</div>
				</div>
			</div>
		</section>
		<!-- =========== mybreadcrumb  Area end =========== -->



		<!-- ========== catagoris body content area start ========== -->
		<section id="postaoffer1">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-xl-8 col-md-10">
						<div class="form_area">
			<form class="mamunurrashid_form" method="post" action="{% url 'techbusiness:create'%}" enctype="multipart/form-data">
				{% csrf_token %}
					<input type="hidden" name="csrfmiddlewaretoken" value="">
					<div class="mr_group">
					<label for="id_title">Title:</label>
					<input class="mr_select" type="text" name="title" maxlength="255" required id="id_title">
				</div>
				<div class="mr_group">
					<label for="id_category">Category:</label>
					<select class="mr_select" name="category" required id="id_category">
					  <option value="" selected>---------</option>

					  <option value="1">Graphic &amp; Design</option>

					  <option value="2">Content Marketing</option>

					  <option value="3">Music &amp; Audio</option>

					  <option value="4">Music Promotion</option>

				</select>
			</div>
			<div class="mr_group">
				<label for="id_sub_category">Sub_category:</label>
				<input class="mr_select" type="text" name="sub_category" maxlength="200" required id="id_sub_category">
			</div>
			<div class="mr_group">
				<label for="id_credit">Credit:</label>
				<input class="mr_select" type="number" name="credit" step="0.01" required id="id_credit">
			</div>
			<div class="mr_group">
				<label for="id_requirement">Requirement:</label>
				<textarea class="mr_textarea" name="requirement" cols="40" rows="10" required id="id_requirement">
				</textarea>
			</div>
			<div class="mr_group">
				<label for="id_gallery">Gallery:</label>
				<input type="file" name="gallery" accept="image/*" id="id_gallery">
			</div>
			<div class="mr_group">
				<label for="id_delivery">Delivery:</label>
				<input class="mr_select" type="text" name="delivery" value="0" maxlength="120" required id="id_delivery">
			</div>
				<div class="mr_form_btn">
                  <button type="submit">Submit the Post</button>
                </div>  
			</form>
						</div>
					</div>
				</div>
			</div>
		</section>

		<!-- ========== catagoris body content area end ========== -->

		<!-- ========= Our Patner Area Start ============= -->
		<section id="patner">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-lg-6 col-md-10 text-center">
						<h2 class="section-title">Some Feedback</h2>
						<p class="section-text">On the other hand, we denounce with righteous indignation and dislike men who are so
							beguiled and demoralized</p>
					</div>
				</div>
				<div class="row justify-content-center patnet_logo">
					<div class="col-lg-2 col-md-3 col-4">
						<a href="#"><img class="img-fluid wow fadeInUp" data-wow-delay=".4s" src="{% static 'img/p1.png'%}" alt=""></a>
					</div>
					<div class="col-lg-2 col-md-3 col-4">
						<a href="#"><img class="img-fluid wow fadeInUp" data-wow-delay=".5s" src="{% static 'img/p2.png'%}" alt=""></a>
					</div>
					<div class="col-lg-2 col-md-3 col-4">
						<a href="#"><img class="img-fluid wow fadeInUp" data-wow-delay=".6s" src="{%static 'img/p3.png' %}" alt=""></a>
					</div>
					<div class="col-lg-2 col-md-3 col-4">
						<a href="#"><img class="img-fluid wow fadeInUp" data-wow-delay=".7s" src="{%static 'img/p1.png'%}" alt=""></a>
					</div>
					<div class="col-lg-2 col-md-3 col-4">
						<a href="#"><img class="img-fluid wow fadeInUp" data-wow-delay=".8s" src="{% static 'img/p2.png'%}" alt=""></a>
					</div>
					<div class="col-lg-2 col-md-3 col-4">
						<a href="#"><img class="img-fluid wow fadeInUp" data-wow-delay=".9s" src="{%static 'img/p3.png'%}" alt=""></a>
					</div>
					<div class="col-lg-2 col-md-3 col-4">
						<a href="#"><img class="img-fluid wow fadeInUp" data-wow-delay="1s" src="{%static 'img/p1.png' %}" alt=""></a>
					</div>
					<div class="col-lg-2 col-md-3 col-4">
						<a href="#"><img class="img-fluid wow fadeInUp" data-wow-delay="1.1s" src="{%static 'img/p2.png'%}" alt=""></a>
					</div>
					<div class="col-lg-2 col-md-3 col-4">
						<a href="#"><img class="img-fluid wow fadeInUp" data-wow-delay="1.2s" src="{% static 'img/p3.png'%}" alt=""></a>
					</div>
				</div>
			</div>
		</section>
		<!-- ========= Our Patner Area End ============= -->


		<!-- ========= Footer Section Start =========== -->
		<footer id="footer">
			<div class="container">
				<div class="row">
					<div class="col-12 text-center footer-logo">
						<img src="{% static 'img/whitelogo.png'%}" alt=""><br>
						<span class="f-bar"></span>
					</div>
				</div>
				<div class="row f-links">
					<div class="col-lg-3 col-6">
						<h3>Quick Info</h3>
						<ul>
							<li>
								<a href="tel:+8812345678">+88 012 345 678</a>
							</li>
							<li>
								<a href="mailto:support@rixio.com">support@rixio.com</a>
							</li>
							<li>
								<a href="mailto:info@rixio.com">info@rixio.com</a>
							</li>
							<li>
								<p>
									Khan Jahan Ali Road, Khulna, Bangladesh.
								</p>
							</li>
						</ul>
					</div>
					<div class="col-lg-3 col-6">
						<h3>About Us</h3>
						<ul>
							<li>
								<a href="#">Careers</a>
							</li>
							<li>
								<a href="#">Press & Newes</a>
							</li>
							<li>
								<a href="#">Partnerships</a>
							</li>
							<li>
								<a href="#">Privacy Policy</a>
							</li>
							<li>
								<a href="#">Terms of Service</a>
							</li>
						</ul>
					</div>
					<div class="col-lg-3 col-6">
						<h3 class="f-40">Supports</h3>
						<ul>
							<li>
								<a href="#">Contact Support</a>
							</li>
							<li>
								<a href="#">Help & Education</a>
							</li>
							<li>
								<a href="#">Trust & Safety</a>
							</li>
							<li>
								<a href="#">Selling on Raxio</a>
							</li>
							<li>
								<a href="#">Buying on Raxio</a>
							</li>
						</ul>
					</div>
					<div class="col-lg-3 col-6">
						<h3 class="f-40">Social Activity</h3>
						<ul>
							<li>
								<a href="#">Facebook</a>
							</li>
							<li>
								<a href="#">Twitter</a>
							</li>
							<li>
								<a href="#">Linkedin</a>
							</li>
							<li>
								<a href="#">Youtube</a>
							</li>
							<li>
								<a href="#">Google Plus</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</footer>
		<div id="copyright">
			<div class="container">
				<div class="row">
					<div class="col-12 text-center">
						<p>2018 | All Right Reserved By Your Company & <span>Raxio</span></p>
					</div>
				</div>
			</div>
		</div>



		<!-- ========= Footer Section Start =========== -->

		<!--Start ClickToTop-->
		<div class="totop">
			<a href="#top"><i class="fa fa-arrow-up"></i></a>
		</div>
		<!--End ClickToTop-->
	</div>
	<!--End Body Wrap-->
	<!--jQuery JS-->
	<script src="{%static 'js/jquery.2.1.2.min.js'%}"></script>
	<!--Bootstrap JS-->
	<script src="{% static 'js/bootstrap.min.js'%}"></script>
	<!--Wow JS-->
	<script src="{%static 'js/wow.min.js'%}"></script>
	<!--Owl Carousel JS-->
	<script src="{%static 'js/owl.carousel.min.js' %}"></script>
	<!--Venobox JS-->
	<script src="{%static 'js/venobox.min.js'%}"></script>
	<!--Slick Slider JS-->
	<script src="{% static 'js/slick.min.js'%}"></script>
	<!--Main-->
	<script src="{% static 'js/custom.js'%}"></script>
{% endblock %}
</body>